pagopa/terraform-azurerm-v3

jwt_keys/README.md, jwt_keys/main.tf, jwt_keys/variables.tf, jwt_keys/versions.tf
=> feat: Import jwt_keys module from azurerm

docs/MIGRATION_FROM_V2.md, storage_account/README.md, storage_account/variables.tf
- added migration guide into readme
- added tables in main readme to take note of the migrations
Simplify the migration of the components from azurerm v2 to v3
```sh
```
=> fix: Storage account migration guide

.pre-commit-config.yaml, container_app_environment/README.md, container_app_environment/outputs.tf, container_app_environment/template.json, subnet/README.md
=> fix: Add Container app environment output id

container_app_environment/README.md, container_app_environment/main.tf, container_app_environment/template.json, container_app_environment/variables.tf
=> fix: Container app unwanted changes

key_vault/README.md, key_vault/variables.tf
=> feat: Enable RBAC authorization variable added.

docs/MIGRATION_FROM_V2.md, kubernetes_pod_identity/README.md, kubernetes_pod_identity/main.tf
=> feat: Kubernetes pod identity migrated from v2

cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf, load_balancer/main.tf, nat_gateway/README.md, nat_gateway/main.tf, nat_gateway/variables.tf
=> fix: Upgrade from azurerm

key_vault/README.md, key_vault/main.tf, key_vault/variables.tf
=> fix: Key vault regression

kubernetes_cluster/10_outputs.tf, kubernetes_cluster/README.md
same as https://github.com/pagopa/azurerm/pull/255
```sh
```
=> fix: Support for aks cluster 1.24+

elastic_stack/README.md, elastic_stack/main.tf, elastic_stack/variables.tf, elastic_stack/versions.tf, elastic_stack/yaml/SecretProvider.yaml, elastic_stack/yaml/apm.yaml, elastic_stack/yaml/crds.yaml, elastic_stack/yaml/elastic.yaml, elastic_stack/yaml/ingress.yaml, elastic_stack/yaml/kibana.yaml, elastic_stack/yaml/mounter.yaml, elastic_stack/yaml/operator.yaml
align from https://github.com/pagopa/azurerm/tree/main/elastic_stack
```sh
```
=> feat: Add elastic stack

subnet/README.md, subnet/main.tf, subnet/variables.tf
=> fix(subnet): Network policies

storage_account/README.md, storage_account/main.tf, storage_account/variables.tf
=> fix(storage_account): Disable cross_tenant_replication_enabled

cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf
=> fix: Upgrade submodules

eventhub/README.md, eventhub/main.tf, eventhub/variables.tf
=> fix: Event hub minimum_tls_version, public_network_access_enabled, zone_redundant

cosmosdb_account/main.tf
https://github.com/pagopa/azurerm/pull/292
```sh
```
=> fix(comsos_db): Private endpoint with capabilities

cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf, storage_management_policy/main.tf
=> fix: Management policy list deprecated

jwt_keys/README.md, jwt_keys/main.tf, jwt_keys/variables.tf
=> fix(jwt_keys): Add default values to avoid replace resource

function_app/main.tf
=> fix(function_app): Default azurerm_storage_management_policy set to -1

function_app/main.tf
=> fix(function_app): Try fix storage management policy (default to 1)

tls_checker/main.tf, tls_checker/templates/tls-cert.yaml.tpl, tls_checker/variables.tf, tls_checker/versions.tf
Add tls_checker module
```sh
```
=> feat: Add tls checker

key_vault/main.tf, key_vault/variables.tf
=> feat: Add public_network_access_enabled bool variable

virtual_network_peering/main.tf
=> fix: Fix peering target name

function_app/README.md, function_app_slot/README.md, storage_account/README.md
=> docs: Minor fix to function_app, function_app_slot and storage_account README.md

storage_account/README.md, storage_account/tests/resources.tf
=> chore(storage_account): Fix storage test and readme

storage_object_replication/tests/README.md, storage_object_replication/tests/backend.ini, storage_object_replication/tests/main.tf, storage_object_replication/tests/outputs.tf, storage_object_replication/tests/resources.tf, storage_object_replication/tests/terraform.sh, storage_object_replication/tests/variables.tf
=> chore(storage_object_replication): Add tests

function_app/tests/terraform.sh, function_app_slot/tests/terraform.sh, nat_gateway/README.md, nat_gateway/main.tf, nat_gateway/tests/README.md, nat_gateway/tests/backend.ini, nat_gateway/tests/main.tf, nat_gateway/tests/outputs.tf, nat_gateway/tests/resources.tf, nat_gateway/tests/terraform.sh, nat_gateway/tests/variables.tf, nat_gateway/variables.tf, storage_account/tests/terraform.sh, storage_object_replication/tests/terraform.sh
=> chore(nat_gateway): Add test

.pre-commit-config.yaml, cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf, storage_account/README.md, storage_account/tests/resources.tf, storage_account_customer_managed_key/tests/resources.tf, storage_object_replication/tests/resources.tf
=> chore: Fix main with readme and upgrade reference to internal modules

nat_gateway/tests/resources.tf, nat_gateway/tests/variables.tf
=> chore(nat_gateway): Fix test

tls_checker/main.tf, tls_checker/templates/tls-cert.yaml.tpl, tls_checker/variables.tf
- added affinity
- improved helm
```sh
```
=> fix: Added affinitiy and update tls-checker module

api_management/main.tf, app_gateway/main.tf, container_registry/main.tf, key_vault/main.tf, kubernetes_cluster/02_monitor_aks.tf, kubernetes_cluster_udr/02_monitor_aks.tf, postgres_flexible_server/02_monitor_flexible.tf, vpn_gateway/main.tf
Update the `azurerm_monitor_diagnostic_setting` resources 
Property `log` is deprecated in favour of the `enabled_log` property and will be removed in version 4.0 of the AzureRM Provider.
```sh
```
=> chore: azurerm_monitor_diagnostic_setting enabled_log

dns_forwarder/README.md, dns_forwarder/main.tf
https://learn.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#network-profile
```sh
```
=> fix: Removed deprecated integration profile from dns forwarder

azure_devops_agent/README.md, azure_devops_agent/main.tf, azure_devops_agent/variables.tf
=> feat: Add devops agent encryptionset var for pci

load_balancer/outputs.tf
=> feat: Add backend pool id in output

key_vault/README.md, key_vault/versions.tf
increased minimum provider version to support used tf block "enabled_logs"
```sh
```
=> fix: Minimum provider version requirement

function_app/README.md, function_app/main.tf, function_app/variables.tf
Added function_app module documentation
```sh
```
=> feat: Added function app documentation

cdn/README.md, cdn/variables.tf
Removed unused variable in cdn module
```sh
```
=> fix: Removed unused variable

postgres_flexible_server/tests/resources.tf
=> fix: Postgresql flexible server - pre-commit issue

azure_devops_agent/main.tf
=> feat: Azure devops > Updated ssh key name to avoid conflicts

azure_devops_agent/README.md
updated azdo_agent readme
fix wrong information in readme
```sh
```
=> fix: Updated azdo agent doc

.utils/run_docker_pre_commit.sh, .utils/terraform_run_all.sh, azure_devops_agent/README.md, azure_devops_agent/main.tf, azure_devops_agent/variables.tf, azure_devops_agent_custom_image/README.md, azure_devops_agent_custom_image/main.tf, azure_devops_agent_custom_image/variables.tf, cert_mounter/README.md
- enabled location as parameter in packer
- fix default value for type of vm scaleset image
Allow durign creation of packer image to choose the location where the image will be put
```sh
```
=> fix: Azdo location for custom image

storage_account/README.md
Updated storage account documentation to show how to setup a storage account with private network
```sh
```
=> chore: Updated storage account docs

azure_devops_agent/script-config.json, azure_devops_agent/script-config.sh
Restore script config for azure devops
Some projects (IO) use old Azure DevOps configuration, so we need to maintain the backward compatibility
```sh
```
=> fix: Restore script config for azure devops

azure_devops_agent/script-config.sh
=> fix: Update script-config.sh

api_management/README.md, kubernetes_cluster_udr/01_main.tf, storage_account/README.md, storage_account/main.tf
=> chore: Fix main

azure_devops_agent_custom_image/README.md, azure_devops_agent_custom_image/packer/script-config.sh
=> feat: Azdo install script checks

application_insights_web_test_preview/main.tf, application_insights_web_test_preview/variables.tf
=> [#IOPLT-124] Externalize Alert description on Web Availability Test

elastic_stack/README.md, elastic_stack/logs-generic/component_logs-generic-mappings.json, elastic_stack/logs-generic/component_logs-generic-settings.json, elastic_stack/logs-generic/data_view.json, elastic_stack/logs-generic/ilm_policy_logs-generic.json, elastic_stack/logs-generic/index_template_logs-generic.json, elastic_stack/main.tf, elastic_stack/variables.tf, elastic_stack/versions.tf, elastic_stack/yaml/SecretProvider.yaml, elastic_stack/yaml/agent.yaml, elastic_stack/yaml/apm.yaml, elastic_stack/yaml/crds.yaml, elastic_stack/yaml/elastic.yaml, elastic_stack/yaml/ingress_apm.yaml, elastic_stack/yaml/ingress_elastic.yaml, elastic_stack/yaml/ingress_kibana.yaml, elastic_stack/yaml/kibana.yaml, elastic_stack/yaml/mounter.yaml, elastic_stack/yaml/operator.yaml
Sync this module with the changes made in azurerm v2
```sh
```
=> feat: ELK sync with azurerm v2

kubernetes_cluster/01_main.tf
=> fix: Aks added check in case log analytics is null

azure_devops_agent_custom_image/README.md, dns_forwarder_vm_image/README.md, dns_forwarder_vm_image/main.tf, dns_forwarder_vm_image/outputs.tf, dns_forwarder_vm_image/packer/azdo-agent.pkr.hcl, dns_forwarder_vm_image/packer/docker-compose.yml, dns_forwarder_vm_image/packer/script-config.sh, dns_forwarder_vm_image/packer/variables.pkr.hcl, dns_forwarder_vm_image/variables.tf, dns_forwarder_vm_image/versions.tf
- added module
- added packer with docker compose for core dns
Allow to create a VM image with coredns already setup with docker compose
```sh
```
=> feat: Packer for dns forwarder vm image

container_app_job_gh_runner/README.md, container_app_job_gh_runner/main.tf, container_app_job_gh_runner/tests/resources.tf, container_app_job_gh_runner/tests/variables.tf, container_app_job_gh_runner/variables.tf
Improve module documentation and variable refactoring:
- `workspace_id` doesn't exist anymore
- `network` change:
- `rg_vnet` is now `vnet_resource_group_name`
- `vnet` is now `vnet_name`
- `cidr_subnets` is now `subnet_cidr_block`
Improving documentation is a good thing.
Variables are easier to understand now.
Module is still unused so these breaking changes don't harm anyone
```sh
```
=> feat: Improve documentation for GitHub self hosted runner module

container_app_job_gh_runner/variables.tf
=> feat: Fix prefix - pr

azure_devops_agent/README.md, azure_devops_agent/main.tf, azure_devops_agent/variables.tf
Added support to zonal vmss
```sh
```
=> Feat azdo zones

kubernetes_cluster_udr/01_main.tf, kubernetes_cluster_udr/10_outputs.tf, kubernetes_cluster_udr/99_variables.tf
=> feat: Add encryption set for udr cluster

storage_account/main.tf
=> feat: Added sa immutability condition for backward compatibility

load_balancer/main.tf
=> feat: Empty string to null for public ip

kubernetes_prometheus_install/README.md, kubernetes_storage_class/README.md, kubernetes_storage_class/main.tf, postgres_flexible_server/README.md
fix warnings in Docs
```sh
```
=> chore: Docs fixed

postgres_flexible_server/02_monitor_flexible.tf
=> feat: Removed deprecated retention policy from postgres diagnostic settings

kubernetes_cluster_velero/01_main.tf, kubernetes_cluster_velero/99_variables.tf, kubernetes_cluster_velero/README.md
=> feat: Velero sa backup

function_app/main.tf, function_app_slot/main.tf
Reverts pagopa/terraform-azurerm-v3#192
=> fix: Add variable to manage network access to durable function app storage account

app_service/main.tf
=> fix: App service hidden links

kubernetes_cluster_velero/01_main.tf
=> feat: Fix velero sa v2

github_federated_identity/README.md, github_federated_identity/locals.tf, github_federated_identity/tests/main.tf, github_federated_identity/versions.tf
Upgrade upper version limit constraint to 3.84
`io-sign` is being upgraded to 3.84
```sh
```
=> fix: Upgrade maximum version of github_federated_identity module - [EC-58]

function_app/main.tf
=> fix: Fix Internal Storage Account Info ternary condition

app_service_slot/README.md, app_service_slot/versions.tf
Version constraint app service slot
Some module needs azurerm >= 3.76 and this one is incompatible
```sh
```
=> feat: Update version constraint of app_service_slot

cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf, kubernetes_cluster_velero/01_main.tf, kubernetes_cluster_velero/README.md
Upgrade internal dependencies
Dependency hell. Inner constraints prevent clients to use the declared compatible version
```sh
```
=> feat: Upgrade internal dependencies - [EC-87]

function_app_slot/main.tf, function_app_slot/variables.tf
Refactor health_check_maxpingfailures assignment
The variable `health_check_maxpingfailures` was not used and TF used to apply `0` as default value instead of the desired `10`
```sh
```
=> fix: Fix health check eviction time assignment in function app slot module - [EC-94]

cdn/README.md, cdn/main.tf, function_app/README.md, function_app/main.tf, kubernetes_cluster_velero/01_main.tf, kubernetes_cluster_velero/README.md
Allow to use the last version of azurerm v3.85
```sh
```
=> feat: Upgrated internals modules

dns_forwarder_lb_vmss/README.md, dns_forwarder_lb_vmss/variables.tf
=> fix: Dns forwarder variable

monitoring_function/01_main.tf, monitoring_function/99_variables.tf, monitoring_function/README.md
=> feat: monitoring function alert configuration

monitoring_function/01_main.tf
=> feat: Fix body compare strategy

monitoring_function/01_main.tf
=> feat: Fix alert names

monitoring_function/01_main.tf, monitoring_function/README.md
=> feat: Fix monitoring

azure_devops_agent_custom_image/README.md, azure_devops_agent_custom_image/main.tf, azure_devops_agent_custom_image/packer/azdo-agent.pkr.hcl, azure_devops_agent_custom_image/packer/variables.pkr.hcl, azure_devops_agent_custom_image/variables.tf
=> feat: Added packer vnet build name

cdn/README.md, cdn/main.tf, cdn/outputs.tf, cdn/variables.tf, monitoring_function/01_main.tf
Add diagnostic settings to CDN profile module
Export CDN profile resource id
Logs and metrics must be enabled on CDN endpoint and exporting CDN profile id is useful as exporting CDN endpoint id
```sh
```
=> feat: Add diagnostic settings to CDN profile - [EC-173]

storage_account/README.md, storage_account/main.tf, storage_account/tests/main.tf, storage_account/tests/resources.tf, storage_account/variables.tf, storage_account/versions.tf
Add storage denfeder to storage account module keeping compatibility with existing thread protection resource.
Adapting to the new pricing model. However, the old one could be more convenient (pay as you go vs fixed price of 10€/mo)
```sh
```
=> feat: Update Storage Account module with Storage Defender resource - [EC-181]

function_app/README.md, function_app/main.tf, function_app/tests/main.tf, function_app/variables.tf, function_app/versions.tf
Add support to cusotmize defender for storage account in function app module
Driving the wanted defender solution
```sh
```
=> feat: Add storage account defender variables to function app module - [EC-199]

container_app_job_gh_runner/README.md
Update documentation
Adding more details
```sh
```
=> docs: Update Container App Job GitHub Runner documentation

container_app_job_gh_runner/README.md, container_app_job_gh_runner/variables.tf, container_app_job_gh_runner/versions.tf
Update supported azurerm versions
Update container app job default docker image
```sh
```
=> feat: Update Container App Job runner default image tag

app_service/README.md, app_service/outputs.tf, function_app/README.md, function_app/outputs.tf, redis_cache/README.md, redis_cache/outputs.tf, storage_account/README.md, storage_account/outputs.tf
Add resource group name as output of storage account, function app, redis and app service modules
Need to consume them
```sh
```
=> chore: Add resource group name in modules' outputs

cdn/README.md, cdn/main.tf, dns_forwarder_lb_vmss/README.md, dns_forwarder_lb_vmss/main.tf, function_app/README.md, function_app/main.tf, kubernetes_cluster_velero/01_main.tf, kubernetes_cluster_velero/README.md, monitoring_function/01_main.tf, monitoring_function/README.md
=> feat: Upgrade internal modules to v7.64.0

kubernetes_velero_backup/01_main.tf, kubernetes_velero_backup/99_variables.tf, kubernetes_velero_backup/README.md
=> feat: Velero backup alert

app_service/README.md, app_service/main.tf, app_service/tests/resources.tf, app_service/variables.tf
added variable configuration for zone balancing
removed unused variable
`plan_kind` variable has been removed because it was not used
```sh
```
=> feat: Update linux service plan

function_app/main.tf
Replace hardcoded values with other variables
```sh
```
=> fix: Replace sa durable function hardcoded values with storage account info

monitoring_function/01_main.tf
=> feat: Set automitigate to monitor alert

monitoring_function/01_main.tf
=> fix: Alert automitigate

cdn/README.md, cdn/main.tf, data_indexer/README.md, data_indexer/storage.tf, dns_forwarder_lb_vmss/README.md, dns_forwarder_lb_vmss/main.tf, function_app/README.md, function_app/main.tf, kubernetes_cluster_velero/01_main.tf, kubernetes_cluster_velero/README.md, monitoring_function/01_main.tf, monitoring_function/README.md
=> chore: Bump versions

CODEOWNERS
Add `engineering-team-cloud-eng` team as CODEOWNERS
```sh
```
=> chore: Add engineering-team-cloud-eng team as CODEOWNERS
